name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and NPM
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install project dependencies
        run: npm install  # Adjust this command based on your project's build process

      - name: Build project
        run: npm run build  # Adjust this command based on your project's build process

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install rsync
        run: sudo apt-get install -y rsync

      - name: Deploy to VPS
        run: |
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./ ubuntu@ec2-15-207-115-79:/var/www/html
